name: Package MoneyLooter

on:
  push:
    tags:
      - "*"
    paths-ignore:
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MoneyLooter
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and upload MoneyLooter
        uses: BigWigsMods/packager@master
        with:
          args: -p 1098459 -a qKQxDo6x -w 26844
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWI_API_TOKEN: ${{secrets.WOWI_API_TOKEN}}
