name: Package MoneyLooter

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'


jobs:
  package:
    strategy:
      matrix:
        type: [retail, classic, cata]
        
        include:
          - type: retail
            pkgmeta: .pkgmeta
          - type: classic
            pkgmeta: .pkgmeta_classic
          - type: cata
            pkgmeta: .pkgmeta_cata
          # - type: wrath
          #   pkgmeta: .pkgmeta_wrath
          # - type: bcc
          #   pkgmeta: .pkgmeta_bcc

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@master
        with:
          args: -p 1098459 -a qKQxDo6x -w 26844 -g ${{matrix.type}} -m ${{matrix.pkgmeta}}
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWI_API_TOKEN: ${{secrets.WOWI_API_TOKEN}}
